elastos/Elastos.NET.Carrier.Native.SDK

README.md

- added flatcc as dependency in macOs
- solution for issue with gettext in homebrew
- simplify docker commands
Please accept my PR. Thank you

Update README.MD - macOs, docker

---

tests/api/carrier/friend_invite_test.c
tests/api/carrier/friend_message_test.c
tests/api/test_helper.c
tests/include/test_context.h
tests/robot/cmd.c
tests/robot/robot.c

introduce “request-response” mechanism for fadd/faccept command

elatests bugfix

---

README.md
THANKS.md

1. Update docs about how to generate API docs;
2. Update dependency projects to thank

update README and THANKS

---

tests/include/cond.h

Fix gettimeofday() not defined in tests.

Fix compile warnings

---

README.md
THANKS.md

Correct the miss writing: armeab_v7a --> armeabi-v7a.

Docs readme

---

src/carrier/ela_carrier.h
src/session/CMakeLists.txt
src/session/session.c

1. Add pjlib/pjlib-util/pjnath errors to ELAF_ICE facility errors.
2. Removed unused macro.

Modify error-handling function and remove an unused macro.

---

.travis.yml
tests/robot/cmd.c

Build debug when the tag name star with "internal-test". (test for androidSDK)

build debug for internal-test

---

apps/file/filetrans.c
src/filetransfer/CMakeLists.txt
src/filetransfer/ela_filetransfer.h
src/filetransfer/filerequests.h
src/filetransfer/filetransfer.c
src/filetransfer/message.h
src/session/ela_session.h
src/session/session.c

1. timeout mechanism for file transfer unhandled requests
2. fix filentry_t release in elafile demo
3. file transfer minor fix
4. amend file transfer doc
5. file transfer: allow user to send zero length data

miscellaneous file transfer refinement

---

src/filetransfer/ela_filetransfer.h
src/filetransfer/filetransfer.c

Fixed the bug about fileTransfer.

Fixed the bug about fileTransfer.

---

src/filetransfer/filetransfer.c

We strip pure filename from parameters file info of "ela_filetransfer_new" and "ela_filetransfer_add" APIs.

fixbug: use pure filename when transfering meta fileinfo

---

README.md

Related to https://github.com/elastos/Elastos.NET.Carrier.Native.SDK/issues/173

 Updated README.md regarding Raspberry Pi

---

CHANGELOG.md

modify CHANGELOG.md

---

.travis.yml
CHANGELOG.md
cmake/ExternalCMakeArgs.cmake
cmake/ExternalConfigureArgs.cmake
deps/Elastos.NET.Hive.Native.SDK/CMakeLists.txt
src/carrier/CMakeLists.txt
src/carrier/dstore_wrapper.c
src/carrier/dstore_wrapper.h
src/carrier/ela_carrier.c

merge three commits from master to release-v.5.3 and modify CHANGELOG.MD.

release-v5.3.2

---

CHANGELOG.md

modify CHANGELOG.md of release v5.3.2

---

deps/libcrystal/CMakeLists.txt

update crystal to release-v1.0.5

update crystal to release-v1.0.5

---

.travis.yml
deps/libcrystal/CMakeLists.txt

update crystal to release-v1.0.5

update crystal to releasev1.0.5

---

CHANGELOG.md

modify CHANGELOG.md for release v5.3.3

modify CHANGELOG.md for release v5.3.3

---

tests/apitests/api/filetransfer/filetransfer_file_test.c

Move high-level-based file-transfer-related test cases.

---

config/carrier.conf
src/carrier/express.c
src/carrier/http_client.c
src/carrier/http_client.h

1. fix bulkmsg pull issue.
2. add express node config.

Feat receipt

---

src/carrier/ela_carrier.c

- mprovement on internal implementation of ela_send_message_xxx APIs
- a bugfix for friend request notificafication

Improvement on internal implementation of ela_send_message_xxx APIs.
